### ISSUE TITLE
Mutating Webhook: Multiple inline mutation does not work into `stringData` secret

### ISSUE THREAD

**Issue by anthonyhaussman** [bank-vaults/bank-vaults.dev#92]
**Describe the bug**

Using the vault-secrets mutating webhook, I'm unable to replace multiple secrets inside the same key, or replace secrets inside a larger string of text.

I understood the feature has been implemented via:
 - https://github.com/banzaicloud/bank-vaults/issues/1001
 - https://github.com/banzaicloud/bank-vaults-docs/pull/42

But I can't mutate my secret.

**Steps to reproduce the issue:**

I want to specify, the creation of a simple secret with the same Vault path is well mutating:
```
# This is working
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-ha-test
  namespace: "rabbitmq"
  labels:
    vault.security.banzaicloud.io/vault-namespace: rabbitmq
    vault.security.banzaicloud.io/vault-role: rabbitmq-ha
    vault.security.banzaicloud.io/vault-serviceaccount: rabbitmq-ha
type: Opaque
data:
  ## "vault:secret/data/bot/service/shared/testyli#aaa" accessible for everyone
  rabbitmq-password: "JHt2YXVsdDpzZWNyZXQvZGF0YS9ib3Qvc2VydmljZS9zaGFyZWQvdGVzdHlsaSNhYWF9"
```

But when I want to use  multiple inline mutations:
```
# Not working
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-ha-load-definition-test
  namespace: "rabbitmq"
  annotations:
    vault.security.banzaicloud.io/vault-namespace: rabbitmq
    vault.security.banzaicloud.io/vault-role: rabbitmq-ha
    vault.security.banzaicloud.io/vault-serviceaccount: rabbitmq-ha
type: Opaque
stringData:
  load_definition.json: |
      "users": [
        {
          "name": "admin",
          "password": "${vault:secret/data/bot/service/shared/testyli#aaa}"
        }
      ]
```

Using this deployment for test:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-vault
  namespace: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-vault
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-namespace: rabbitmq
        vault.security.banzaicloud.io/vault-role: rabbitmq-ha
        vault.security.banzaicloud.io/vault-serviceaccount: rabbitmq-ha
      labels:
        app.kubernetes.io/name: test-vault
      name: test-vault
      namespace: rabbitmq
    spec:
      containers:
        - command:
            - sh
            - -c
            - echo $RABBITMQ_PASSWORD && echo going to sleep... && sleep infinity
          env:
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                key: rabbitmq-password
                name: rabbitmq-ha-test
          image: alpine
          imagePullPolicy: Always
          name: alpine
          volumeMounts:
          - mountPath: /app
            name: load-definition-volume
            readOnly: true
      restartPolicy: Always
      serviceAccount: rabbitmq-ha
      serviceAccountName: rabbitmq-ha
      volumes:
      - name: load-definition-volume
        secret:
          defaultMode: 420
```

Taking a look:
```
# Simple secret via environment variable reference is well mutated
k -n rabbitmq logs test-vault-5b77546544-ljjx4
Defaulted container "alpine" out of: alpine, copy-vault-env (init)
bbb
going to sleep...

# File mount is not mutated
k -n rabbitmq exec -ti test-vault-5b77546544-ljjx4 -- cat /app/load_definition.json 
Defaulted container "alpine" out of: alpine, copy-vault-env (init)
"users": [
  {
    "name": "admin",
    "password": "${vault:secret/data/bot/service/shared/testyli#aaa}"
  }
]
```

**Expected behavior**
Secrets with multiple inline mutation vault secrets are working.
Old documentation seems to say that it was needed to set the environment variable `INLINE_MUTATION: true` on the webhook but seems to be the default today.
